baseURL = "www.raizin.net"
languageCode = "ja"
title = "WEBシステム開発・高速ホームページ作成・WEBマーケティング | 山口県山口市　株式会社RAIZIN"

[params]
  # In most cases you will only want to use either one of these. If you have Google Analytics included in your GTM tags don't put your GA ID here. Otherwise your data might be useless.
  google_analytics_id = "UA-201887699-1"
  google_tag_manager_id = "6002187448"

  [params.homepage]
    show_call_box = true
    hide_view_all_services = false  # set to true to hide the View All Services button

  [params.logo]
    mobile = "images/logo/logo-mobile.webp"
    mobile_height = "36px"
    desktop = "images/logo/logo.png"
    desktop_height = "59px"
    alt = "RAIZIN Inc."

  [params.homepage_meta_tags]
    meta_description = "IoT技術、Webアプリ開発、Webマーケティングを主な業務としています。DXに係るコンサル及びシステム開発から、企業の生産性向上、コーポレートサイトの構築、企業用ホームページ制作、SEO対策、パフォーマンスの高いWebサイトの制作を行っています。認定経営革新等支援機関、スマートSMEサポーター（認定情報処理支援機関）として、小規模事業者・中小企業の生産性向上に資するITツールを提供するITベンダー等のIT導入支援・経営状況の把握、事業計画作成、事業計画実行等支援等の業務を行っています。"
    meta_keywords = "Webアプリ開発,Webマーケティング,高速WEBサイト,高速サイト,爆速ホームページ,IoTコンサル,認定経営革新等支援機関,スマートSMEサポーター,認定情報処理支援機関,IT導入支援事業者,IT×経営,ITコンサル,PWA,SPA"
    meta_og_title = "Copyright © 2018 RAIZIN Inc. ALLRIGHT RESERVED"
    meta_og_type = "website"
    meta_og_url = "https://raizin.net"
    meta_og_image = "https://raizin.net"
    meta_og_description = "高速サイト、GOlang,Go言語,Jamstack,PWA,SPA,Hugo,Alpine.js,Tailwind,IoT,BLE"
    meta_twitter_card = "summary"
    meta_twitter_site = "@raizin.net"
    meta_twitter_creator = "@raizin.net"

  [params.team]
    summary_large_truncate = 120  # How many characters to include in the summary of the team bios (large layout) before truncating

  [params.footer]
    copyright_text = 'IoT-Services, AP-Development, JAMstack, FastSite, Marketing, IT-Consulting by RAIZIN Inc.'

[menu]
  # Main Menu
  [[menu.main]]
    name = "Services"
    url = "/services/"
      weight = 1

  [[menu.main]]
      name = "Webmarketing"
      url = "/webmarketing/"
      weight = 2

  [[menu.main]]
      name = "Post"
      url = "/post/"
      weight = 3

  [[menu.main]]
      name = "About"
      url = "/about/"
      weight = 5

  [[menu.main]]
      name = "Contact"
      url = "/contact/"
      weight = 6

  # Footer Menu
  [[menu.footer]]
    name = "Home"
    url = "/"
      weight = 1

  [[menu.footer]]
    name = "Services"
    url = "/services/"
      weight = 2

  [[menu.footer]]
    name = "Webmarketing"
    url = "/webmarketing/"
      weight = 3

  [[menu.footer]]
    name = "Post"
    url = "/post/"
      weight = 4

  [[menu.footer]]
      name = "Links"
      url = "/links/"
      weight = 5

  [[menu.footer]]
      name = "About"
      url = "/about/"
      weight = 6

  [[menu.footer]]
    name = "Contact"
    url = "/contact/"
      weight = 7
