baseURL = "www.raizin.net"
languageCode = "ja"
title = "（株）RAIZIN"

[params]
  # In most cases you will only want to use either one of these. If you have Google Analytics included in your GTM tags don't put your GA ID here. Otherwise your data might be useless.
  google_analytics_id = ""
  google_tag_manager_id = ""

  [params.homepage]
    show_call_box = true
    hide_view_all_services = false  # set to true to hide the View All Services button

  [params.logo]
    mobile = "images/logo/logo-mobile.png"
    mobile_height = "36px"
    desktop = "images/logo/logo.png"
    desktop_height = "36px"
    alt = "RAIZIN Inc."

  [params.homepage_meta_tags]
    meta_description = "（株）RAIZINは、IoT技術、Webアプリ開発、Webマーケティングを主な業務としています。"
    meta_og_title = "Copyright © 2018 RAIZIN Inc. ALLRIGHT RESERVED"
    meta_og_type = "website"
    meta_og_url = "https://raizin.net"
    meta_og_image = "https://raizin.net"
    meta_og_description = "（株）RAIZINは、IoT技術、Webアプリ開発、Webマーケティングを主な業務としています。"
    meta_twitter_card = "summary"
    meta_twitter_site = "@raizin.net"
    meta_twitter_creator = "@raizin.net"

  [params.team]
    summary_large_truncate = 120  # How many characters to include in the summary of the team bios (large layout) before truncating

  [params.footer]
    copyright_text = 'by RAIZIN Inc.'

[menu]
  # Main Menu
  [[menu.main]]
    name = "Services"
    url = "/services/"
      weight = 1


  [[menu.main]]
      name = "Post"
      url = "/post/"
      weight = 2

  [[menu.main]]
      name = "Team"
      url = "/team/"
      weight = 3

  [[menu.main]]
      name = "About"
      url = "/about/"
      weight = 4

  [[menu.main]]
      name = "Contact"
      url = "/contact/"
      weight = 5

  # Footer Menu
  [[menu.footer]]
    name = "Home"
    url = "/"
      weight = 1

  [[menu.footer]]
    name = "Contact"
    url = "/contact/"
      weight = 2
